# Generated by Django 5.2.12 on 2026-03-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulizarequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
